// Generated by CoffeeScript 1.4.0
(function() {

  describe("Article", function() {
    var article, content, date, html, section, title;
    article = title = content = date = section = html = null;
    beforeEach(function() {
      article = new Article();
      title = "Test title";
      content = "<p>Test Content 1</p><p>Test Content 2</p><p>Test Content 3</p>";
      date = new Date();
      section = "Test section";
      return html = "<html>\n  <head></head>\n  <body>\n    <div class=\"container\">\n      <div class=\"LHS\">\n        <div id=\"articleContent\" class=\"LHSContent\">\n          <div class=\"LHSBorderBox\">\n            <table class=\"LinkTable\">\n              <tbody>\n                <tr>\n                  <td>\n                    <h1>Test title</h1>\n                  </td>\n                </tr>\n              </tbody>\n            </table>\n          </div>\n          <div id=\"masterContent\" class=\"fontSize2\">\n            <div class=\"ArticleContent_Outer\">\n              <div class=\"ArticleContent_Inner\">\n                <p class=\"ArticleIntro\">Test Content 1</p>\n              </div>\n            </div>\n            <div class=\"ArticleContent_Outer\">\n              <div class=\"ArticleContent_Inner\">\n                <p class=\"ArticleIntro\">Test Content 2</p>\n              </div>\n            </div>\n            <div class=\"ArticleContent_Outer\">\n              <div class=\"ArticleContent_Inner\">\n                <p class=\"ArticleIntro\">Test Content 3</p>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </body>\n</html>";
    });
    it("should be able to set title", function() {
      article.set_title(title);
      return expect(article.title).toEqual(title);
    });
    it("should be able to set content", function() {
      article.set_content(content);
      return expect(article.content).toEqual(content);
    });
    it("should be able to set date", function() {
      article.set_date(date);
      return expect(article.date).toEqual(date);
    });
    it("should be able to set section", function() {
      article.set_section(section);
      return expect(article.section).toEqual(section);
    });
    return it("should parse webpage to set all attr", function() {
      article.parse(html);
      expect(article.title).toEqual(title);
      expect(article.section).toEqual(section);
      expect(article.content).toEqual(content);
      return expect(article.date).toEqual(date);
    });
  });

}).call(this);
